### PR TITLE
add Wild World to City Folk label 

### LINKED ISSUE #12: AC: Wild World music?
is it just me or is there no music from wild world?

(unrelated, but i made a french translation in one of the forks! i'm not good at github, so good luck on importing it or whatever xP)

### PR DESCRIPTION
**Pull request by Azekthi**
Closes #12

### CODE REVIEW

**Comment by OpenSauce04** [comment]
While similar, they are *technically* different soundtracks, so maybe they should be listed separately?

**Comment by Azekthi** [comment]
@OpenSauce04 I never played CF, but I spent many hours playing WW, and despite that, I can still say CF's soundtrack is the same as WW's. There's no reason to duplicate their menu options, or worse, add more sound files to bloat the app when CF's soundtrack fulfills WW's role perfectly.

**Comment by OpenSauce04** [comment]
Fair enough, as you were

**Review by mn6 — APPROVED** [review]

**Comment by mn6** [comment]
Thank you for your contribution!

**Pull request merged**
